name: build

on:
  pull_request:
  push:
    branches-ignore: [main]

permissions:
  contents: read

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Read version
        run: echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV
      
      - uses: docker/setup-buildx-action@v3
      
      # Build base layer (local)
      - name: Build base layer (local)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.base
          build-args: VERSION=${{ env.VERSION }}
          push: false
          load: true
          tags: local/haskell-tex-dev:base-${{ github.sha }}
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Build haskell layer (local)
      - name: Build haskell layer (local)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.haskell
          build-args: |
            BASE_IMAGE=ghcr.io/git-steb/haskell-tex-dev:base-latest
            VERSION=${{ env.VERSION }}
          push: false
          load: true
          tags: local/haskell-tex-dev:haskell-${{ github.sha }}
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Build tex layer (local)
      - name: Build tex layer (local)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.tex
          build-args: |
            BASE_IMAGE=ghcr.io/git-steb/haskell-tex-dev:haskell-latest
            VERSION=${{ env.VERSION }}
          push: false
          load: true
          tags: local/haskell-tex-dev:tex-${{ github.sha }}
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Test image functionality (local images)
        run: |
          set -euo pipefail
          echo "Testing image functionality..."
          echo "Version: $VERSION"
          
          # Test that the base image has the required tools
          echo "Testing base image tools..."
          docker run --rm local/haskell-tex-dev:base-${{ github.sha }} jq --version
          docker run --rm local/haskell-tex-dev:base-${{ github.sha }} gh --version
          
          # Test that the haskell image has the required tools
          echo "Testing haskell image tools..."
          docker run --rm local/haskell-tex-dev:haskell-${{ github.sha }} ghc --version
          docker run --rm local/haskell-tex-dev:haskell-${{ github.sha }} cabal --version
          
          # Test that the tex image has the required tools
          echo "Testing tex image tools..."
          docker run --rm local/haskell-tex-dev:tex-${{ github.sha }} latexmk -v
          
          echo "✅ All builds and tests passed!"

      - name: Build summary
        run: |
          echo "## Build Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "✅ **Base layer**: Built successfully" >> $GITHUB_STEP_SUMMARY
          echo "✅ **Haskell layer**: Built successfully" >> $GITHUB_STEP_SUMMARY
          echo "✅ **TeX layer**: Built successfully" >> $GITHUB_STEP_SUMMARY
          echo "✅ **Tool verification**: All tools available" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Version**: v$VERSION" >> $GITHUB_STEP_SUMMARY
          echo "**Status**: Ready for merge and publish" >> $GITHUB_STEP_SUMMARY
