name: build-and-publish

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Read version
        run: echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV
      
      - uses: docker/setup-buildx-action@v3
      
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      # Build and push base layer
      - name: Build and push base layer
        uses: docker/build-push-action@v6
        with:
          context: build_context
          file: Dockerfile.base
          build-args: VERSION=${{ env.VERSION }}
          push: true
          load: true
          tags: |
            ghcr.io/git-steb/haskell-tex-dev:base-${{ github.sha }}
            ghcr.io/git-steb/haskell-tex-dev:base-latest
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Build and push haskell layer
      - name: Build and push haskell layer
        uses: docker/build-push-action@v6
        with:
          context: build_context
          file: Dockerfile.haskell
          build-args: |
            BASE_IMAGE=ghcr.io/git-steb/haskell-tex-dev:base-${{ github.sha }}
            VERSION=${{ env.VERSION }}
          push: true
          load: true
          tags: |
            ghcr.io/git-steb/haskell-tex-dev:haskell-${{ github.sha }}
            ghcr.io/git-steb/haskell-tex-dev:haskell-latest
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Build and push tex layer (full image)
      - name: Build and push tex layer
        uses: docker/build-push-action@v6
        with:
          context: build_context
          file: Dockerfile.tex
          build-args: |
            BASE_IMAGE=ghcr.io/git-steb/haskell-tex-dev:haskell-${{ github.sha }}
            VERSION=${{ env.VERSION }}
          push: true
          load: true
          tags: |
            ghcr.io/git-steb/haskell-tex-dev:tex-${{ github.sha }}
            ghcr.io/git-steb/haskell-tex-dev:tex-latest
            ghcr.io/git-steb/haskell-tex-dev:latest
            ghcr.io/git-steb/haskell-tex-dev:v${{ env.VERSION }}
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Test image functionality
        run: |
          set -euo pipefail
          echo "Testing image functionality..."
          echo "Version: $VERSION"
          
          # Test that the base image has the required tools
          echo "Testing base image tools..."
          docker run --rm ghcr.io/git-steb/haskell-tex-dev:base-latest jq --version
          docker run --rm ghcr.io/git-steb/haskell-tex-dev:base-latest gh --version
          
          # Test that the haskell image has the required tools
          echo "Testing haskell image tools..."
          docker run --rm ghcr.io/git-steb/haskell-tex-dev:haskell-latest ghc --version
          docker run --rm ghcr.io/git-steb/haskell-tex-dev:haskell-latest cabal --version
          
          # Test that the tex image has the required tools
          echo "Testing tex image tools..."
          docker run --rm ghcr.io/git-steb/haskell-tex-dev:tex-latest latexmk -v
          
          echo "✅ All builds and tests passed!"

      - name: Build summary
        run: |
          echo "## Build and Publish Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "✅ **Base layer**: Built and published" >> $GITHUB_STEP_SUMMARY
          echo "✅ **Haskell layer**: Built and published" >> $GITHUB_STEP_SUMMARY
          echo "✅ **TeX layer**: Built and published" >> $GITHUB_STEP_SUMMARY
          echo "✅ **Tool verification**: All tools available" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Version**: v$VERSION" >> $GITHUB_STEP_SUMMARY
          echo "**Published tags**: latest, v$VERSION" >> $GITHUB_STEP_SUMMARY
