name: Build & Push Docker Image

on:
  push:
    branches: [ main ]
    paths-ignore: [ '**/*.md' ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: docker/setup-buildx-action@v3
      
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build base image first
      - name: Build base image
        id: base
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.base
          push: true
          tags: |
            ghcr.io/git-steb/haskell-tex-dev:base-${{ github.sha }}
            ghcr.io/git-steb/haskell-tex-dev:base-latest
          platforms: linux/amd64

      # Build haskell image using the base image
      - id: hs
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.haskell
          build-args: |
            BASE_IMAGE=ghcr.io/git-steb/haskell-tex-dev:base-${{ github.sha }}
          push: true
          tags: |
            ghcr.io/git-steb/haskell-tex-dev:haskell-${{ github.sha }}
            ghcr.io/git-steb/haskell-tex-dev:latest
          platforms: linux/amd64

      # alias to full-latest (no rebuild)
      - name: Alias full-latest to haskell digest
        run: |
          docker buildx imagetools create \
            --tag ghcr.io/git-steb/haskell-tex-dev:full-latest \
            ghcr.io/git-steb/haskell-tex-dev@${{ steps.hs.outputs.digest }}

      - name: Verify tag
        run: docker buildx imagetools inspect ghcr.io/git-steb/haskell-tex-dev:full-latest
# Trigger workflow
