name: Build & Push Docker Image

on:
  push:
    branches: [ main ]
    paths-ignore: [ '**/*.md' ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: docker/setup-buildx-action@v3
      
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # build/push base layer
      - id: base
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.base
          push: true
          tags: |
            ghcr.io/git-steb/haskell-tex-dev:base-${{ github.sha }}
            ghcr.io/git-steb/haskell-tex-dev:base-latest
          platforms: linux/amd64

      # build/push haskell layer (Haskell only)
      - id: hs
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.haskell
          build-args: BASE_IMAGE=ghcr.io/git-steb/haskell-tex-dev:base-${{ github.sha }}
          push: true
          tags: |
            ghcr.io/git-steb/haskell-tex-dev:haskell-${{ github.sha }}
            ghcr.io/git-steb/haskell-tex-dev:haskell-latest
          platforms: linux/amd64

      # build/push tex layer (Full image: Haskell + TeX)
      - id: tex
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.tex
          build-args: BASE_IMAGE=ghcr.io/git-steb/haskell-tex-dev:haskell-${{ github.sha }}
          push: true
          tags: |
            ghcr.io/git-steb/haskell-tex-dev:tex-${{ github.sha }}
            ghcr.io/git-steb/haskell-tex-dev:tex-latest
            ghcr.io/git-steb/haskell-tex-dev:latest
            ghcr.io/git-steb/haskell-tex-dev:v1.2.0
          platforms: linux/amd64

      - name: Verify all tags
        run: |
          echo "Verifying all container tags..."
          echo "=== Latest (should be full image with Haskell + TeX) ==="
          docker buildx imagetools inspect ghcr.io/git-steb/haskell-tex-dev:latest
          echo "=== v1.2.0 (should be full image with Haskell + TeX) ==="
          docker buildx imagetools inspect ghcr.io/git-steb/haskell-tex-dev:v1.2.0
          echo "=== Tex layer ==="
          docker buildx imagetools inspect ghcr.io/git-steb/haskell-tex-dev:tex-latest
          echo "=== Haskell layer ==="
          docker buildx imagetools inspect ghcr.io/git-steb/haskell-tex-dev:haskell-latest
          echo "=== Base layer ==="
          docker buildx imagetools inspect ghcr.io/git-steb/haskell-tex-dev:base-latest
