name: Release image on tag
on:
  push:
    tags: ['v*']   # runs for v1.1.0 etc.
permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build base image first
      - name: Build base image
        id: base
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.base
          push: true
          platforms: linux/amd64
          tags: |
            ghcr.io/git-steb/haskell-tex-dev:base-${{ github.ref_name }}   # v1.1.0
            ghcr.io/git-steb/haskell-tex-dev:base-${{ github.sha }}

      # Build & push haskell image with the semver tag (and a SHA tag)
      - id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.haskell
          build-args: |
            BASE_IMAGE=ghcr.io/git-steb/haskell-tex-dev:base-${{ github.sha }}
          push: true
          platforms: linux/amd64
          tags: |
            ghcr.io/git-steb/haskell-tex-dev:${{ github.ref_name }}   # v1.1.0
            ghcr.io/git-steb/haskell-tex-dev:haskell-${{ github.sha }}

      # Promote stable aliases to the same digest (no rebuild)
      - name: Alias latest to tag digest
        run: |
          docker buildx imagetools create \
            --tag ghcr.io/git-steb/haskell-tex-dev:latest \
            ghcr.io/git-steb/haskell-tex-dev@${{ steps.build.outputs.digest }}

      - name: Alias base-latest to base digest
        run: |
          docker buildx imagetools create \
            --tag ghcr.io/git-steb/haskell-tex-dev:base-latest \
            ghcr.io/git-steb/haskell-tex-dev@${{ steps.base.outputs.digest }}

      - name: Verify aliases
        run: |
          echo "Verifying latest alias..."
          WANT=${{ steps.build.outputs.digest }}
          GOT=$(docker buildx imagetools inspect ghcr.io/git-steb/haskell-tex-dev:latest \
                | awk '/Digest:/ {print $2; exit}')
          [ "$WANT" = "$GOT" ] || { echo "latest mismatch $WANT != $GOT"; exit 1; }
          
          echo "Verifying base-latest alias..."
          WANT_BASE=${{ steps.base.outputs.digest }}
          GOT_BASE=$(docker buildx imagetools inspect ghcr.io/git-steb/haskell-tex-dev:base-latest \
                | awk '/Digest:/ {print $2; exit}')
          [ "$WANT_BASE" = "$GOT_BASE" ] || { echo "base-latest mismatch $WANT_BASE != $GOT_BASE"; exit 1; }
          
          echo "✅ All aliases verified successfully"

      - name: Output digests for downstream consumption
        run: |
          echo "base_digest=${{ steps.base.outputs.digest }}" >> $GITHUB_OUTPUT
          echo "haskell_digest=${{ steps.build.outputs.digest }}" >> $GITHUB_OUTPUT
          echo "tag=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          echo "sha=${{ github.sha }}" >> $GITHUB_OUTPUT
